# FileUtils is included in a Rakefile automatically
# The following always get executed regardless of task
FileUtils::touch 'entry~'
FileUtils::touch 'blargle.bak'

# As a Rakefile is simply Ruby, we can use methods as usual
# to factor out common code
def delete(pattern)
  files = Dir[pattern]
  rm(files, verbose: true) unless files.empty?
end

# Run with:
# $rake delete_unix_backups
desc "Remove files whose names end with a tilde"
task :delete_unix_backups do
  delete('*~')
end

# Run with:
# $rake delete_windows_backups
desc "Remove files with a .bak extension"
task :delete_windows_backups do
  delete('*.bak')
end

# COMPOSE a task for use on multiple different platforms
desc "Remove Unix and Windows backup files"
task :delete_backups => [:delete_unix_backups, :delete_windows_backups] do
  puts "All backups deleted"
end
